-- migration: enable extensions and create custom types
-- purpose: enable required postgresql extensions and create enum types for flashcard ai
-- affected: database extensions, custom enum types
-- author: flashcard ai team
-- date: 2026-01-11

-- enable moddatetime extension for automatic updated_at timestamp management
-- this extension provides the moddatetime() function used in triggers
create extension if not exists moddatetime schema extensions;

-- create enum type for flashcard source tracking
-- this enum tracks the origin of each flashcard to enable analytics
-- values:
--   'AI': flashcard was generated by ai without modifications
--   'EditedAI': flashcard was generated by ai but modified by user before saving
--   'Manual': flashcard was created manually by user without ai assistance
create type card_source_type as enum ('AI', 'EditedAI', 'Manual');

-- add comment to document the enum type
comment on type card_source_type is 'Tracks the origin/source of flashcard creation: AI-generated, AI-edited, or manually created';
