-- migration: create generation_logs table
-- purpose: log all ai generation operations for analytics and acceptance rate calculation
-- affected tables: generation_logs (new)
-- references: profiles (foreign key)
-- analytics: enables calculation of ai acceptance rate metric
-- author: flashcard ai team
-- date: 2026-01-11

-- create generation_logs table
-- this table records each ai generation session to enable:
--   1. analytics: track usage patterns and acceptance rates
--   2. quota enforcement: verify generation limits (via profiles.generations_count)
--   3. metrics: calculate acceptance rate = (accepted cards / generated_count) per session
-- 
-- acceptance rate calculation:
--   acceptance_rate = count(flashcards where generation_id = X) / generation_logs.generated_count
--   this measures what percentage of ai-generated flashcards users actually save
create table public.generation_logs (
  -- primary key: unique identifier for each generation session
  id uuid primary key default gen_random_uuid(),
  
  -- foreign key: user who initiated the generation
  -- note: intentionally NOT cascade delete - preserve analytics even if user deletes account
  -- this historical data is valuable for product metrics
  user_id uuid not null references public.profiles(id),
  
  -- number of flashcards proposed by ai in this generation session
  -- used as denominator in acceptance rate calculation
  -- must be positive (ai always generates at least 1 card)
  generated_count integer not null,
  
  -- timestamp when generation was executed
  -- used for analytics, trending, and usage pattern analysis
  created_at timestamptz not null default now(),
  
  -- ensure generated_count is positive
  constraint generated_count_positive check (generated_count > 0)
);

-- enable row level security on generation_logs table
-- this is mandatory for all public tables in supabase
alter table public.generation_logs enable row level security;

-- rls policy: authenticated users can view only their own generation logs
-- used when: displaying generation history, calculating personal acceptance rate
create policy "generation_logs_select_own"
  on public.generation_logs
  for select
  to authenticated
  using (auth.uid() = user_id);

-- rls policy: authenticated users can insert generation logs for themselves
-- used when: recording a new ai generation session
-- note: typically called by check_and_reset_quota() function, but policy enables direct inserts
create policy "generation_logs_insert_own"
  on public.generation_logs
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- note: no update or delete policies
-- generation logs are immutable once created to preserve analytics integrity
-- if user account is deleted, logs are retained for product analytics

-- add table comment for documentation
comment on table public.generation_logs is 'Audit log of AI generation sessions for analytics and acceptance rate calculation';

-- add column comments for clarity
comment on column public.generation_logs.user_id is 'User who initiated the generation (logs preserved even if user deleted)';
comment on column public.generation_logs.generated_count is 'Number of flashcards generated by AI in this session (used for acceptance rate calculation)';
comment on column public.generation_logs.created_at is 'Timestamp of generation execution for analytics and usage patterns';
